In [17]:
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score
import numpy as np
from nd_ridge import my_n_ridge

In [18]:
X, y = load_diabetes(return_X_y=True)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=4)

In [20]:
reg = Ridge(alpha=0.1, solver='cholesky')

In [21]:
reg.fit(X_train, y_train)

Ridge(alpha=0.1, solver='cholesky')

In [22]:
Ridge(alpha=0.1, solver='cholesky')

Ridge(alpha=0.1, solver='cholesky')

In [23]:
y_pred = reg.predict(X_test)
y_pred

array([ 79.11687293, 110.53477702, 167.91664171,  56.09370852,
       176.28941373, 143.1207191 , 113.55542675, 119.62484626,
        81.1578992 ,  76.76131678, 100.57883353, 186.51861928,
       176.92787856, 129.16688066, 158.03962815, 140.6919152 ,
       177.98896665, 121.81303789, 108.91384989, 179.34966945,
       216.2571452 , 177.21873025,  55.02285248, 221.15400516,
        64.88561557, 103.11020925, 155.92973833, 173.41810907,
        72.19426363,  79.27174588, 189.87240518, 112.43816609,
       246.03053579, 180.68495859, 102.98204948, 167.1093383 ,
       171.61286368, 160.42495621, 143.75222884, 155.43807956,
       192.81472846, 170.21104819, 233.02444667,  76.45676401,
       232.59483513, 105.94563573, 150.03909319,  70.13429949,
       193.68093275, 137.73383294, 112.56570315, 104.42101972,
       153.7123577 , 216.2568939 ,  62.56545543, 186.12773302,
       102.92375218,  92.71474925, 182.75690638, 218.66313594,
       125.02620187, 102.93275892, 165.7103638 , 240.39

In [24]:
r2_score(y_test, y_pred)

0.46931288533098037

In [25]:
print(reg.coef_)
print(reg.intercept_)

[  44.02063391 -241.69329987  452.98665299  332.04420177  -76.33686744
  -68.52143809 -164.98809083  149.96908118  431.61347417   58.51862681]
150.89053425602808


In [26]:
mrg = my_n_ridge()

In [27]:
reg.fit(X_train, y_train)

Ridge(alpha=0.1, solver='cholesky')

In [28]:
y_pred = reg.predict(X_test)
print(r2_score(y_test, y_pred))
print(reg.coef_)
print(reg.intercept_)

0.46931288533098037
[  44.02063391 -241.69329987  452.98665299  332.04420177  -76.33686744
  -68.52143809 -164.98809083  149.96908118  431.61347417   58.51862681]
150.89053425602808


### why difference ? in sklearn the w[0][0] = 0 in identity matrix

The reason of using [0][0]=0 is that because in our metrix W the first term is basically intercept not slope and we have to multiply Lambda with only slopes.
Thats why first term became zero and lambda is multiplied with only slopes.


In [29]:
i = np.identity(3)
print(i)
i[0][0] = 0
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
